package common.evaluations;

import common.interfaces.RatingEvaluation;

/**
 * Class for calculating the business performance of a company. Returns an EBITDA margin.
 * <p>
 * EBITDA margin is calculated by EBITDA divided by the companies total revenue.
 * <p>
 *   EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortization.
 *   The EBITDA margin is a measure of a company's operating profitability as a percentage of its
 *   total revenue.
 * </p>
 *
 * @author Olivia Svensson
 */
public class BusinessPerformanceEvaluation implements RatingEvaluation {

  private final String symbol;
  private final double EBITDA;
  private final double revenueTTM;
  private double EBITDAMargin;
  private int rating;
  private String description;

  /*
  * Constructor for BusinessPerformanceEvaluation. Calls the method evaluate.
  * */
  public BusinessPerformanceEvaluation(String symbol, double EBITDA, double revenueTTM) {
    this.symbol = symbol;
    this.EBITDA = EBITDA;
    this.revenueTTM = revenueTTM;
    evaluate();
  }

  /*
  * Method for evaluating the EBITDA to the revenue for the past twelve months, which is the EBITDA margin.
  * */
  private void evaluateEBITDAMargin() {
    EBITDAMargin = EBITDA / revenueTTM;
  }

  /*
  * Method for evaluating the EBITDA margin which sets the description variable to a fitting one depending on
  * the performance of the stock.
  * */
  @Override
  public void evaluate() {
    evaluateEBITDAMargin();
    if (EBITDAMargin > 0.20) {
      rating = 5;
      description = "There is an indication that " + symbol + " has a great performance";
    } else if (EBITDAMargin > 0.15 && EBITDAMargin < 0.20) {
      rating = 4;
      description = "There is an indication that " + symbol + " has a good performance";
    } else if (EBITDAMargin > 0.10  && EBITDAMargin < 0.15) {
      rating = 3;
      description = "There is an indication that " + symbol + " has an average performance";
    } else if (EBITDAMargin > 0.05  && EBITDAMargin < 0.10) {
      rating = 2;
      description = "There is an indication that " + symbol + " has an average performance";
    } else if (EBITDAMargin > 0.025  && EBITDAMargin < 0.10) {
      rating = 1;
      description = "There is an indication that " + symbol + " has a weak performance";
    } else {
      rating = 0;
      description = "There is an indication that " + symbol + " has a very weak performance";
    }
  }

  @Override
  public String getSymbol() {
    return symbol;
  }

  /**
   * Method for getting the title of the evaluation.
   * <p>
   * The title corresponds to the type of evaluation that is performed.
   *
   * @return the title of the evaluation.
   */
  @Override
  public String getTitle() {
    return "Business Performance";
  }

  /**
   * Method for getting the subtitle of the evaluation.
   * <p>
   * The subtitle is a short description of the data that the evaluation is based on.
   *
   * @return the subtitle of the evaluation.
   */
  @Override
  public String getSubtitle() {
    return "The business performance evaluation is based on the company’s performance. The"
        + " performance of the company is evaluated based on the EBITDA and the company’s total"
        + " revenue. EBITDA is the earnings of the company before interest, taxes, depreciation,"
        + " and amortization. EBITDA is an alternate measure of profitability to net income."
        + " EBITDA attempts to represent the cash profit generated by the company’s operations."
        + " What is meant by total revenue is how much revenue the company has from recurring"
        + " and non-recurring revenue streams. It is the total amount of income the company brings"
        + " in from selling products and/or services. ";
  }

  /**
   * Method for getting the evaluation method.
   * <p>
   * The evaluation method is a short description of how the evaluation is performed.
   *
   * @return the evaluation method.
   */
  @Override
  public String getEvaluationMethod() {
    return "The business performance of the company is evaluated by calculating the EBITDA margin,"
        + " which is a measure of a company’s operating profitability as a percentage of its total"
        + " revenue. The EBITDA margin is a good indicator for the company’s financial performance."
        + " However, it is not a good indicator for all companies. For companies with high levels"
        + " of debt or companies that consistently purchase expensive equipment for their"
        + " operations, it is not as effective of a measure. The EBITDA margin is calculated by"
        + " dividing the EBITDA with the revenue of the company for the past twelve months."
        + " The EBITDA margin is then graded by how many percentages it is, the higher, the better."
        + " What is considered a good EBITDA margin is industry specific, however it can be"
        + " generalized, which is what we have done. A high EBITDA means that the operating"
        + " expenses are lower in relation to total revenue, meaning that the company’s earnings"
        + " are stable. A low EBITDA margin indicates that the company has issues with its"
        + " profitability as well as cash flow.  We have graded the EBITDA margin as following:"
        + " more than 20% indicates great performance, more than 15% indicates good performance,"
        + " more than 10% indicates an average performance, more than 5% indicates average"
        + " performance, more than 2.5% indicates a weak performance, and less than that indicates"
        + " a very weak performance.";
  }

  @Override
  public String getDescription() {
    return description;
  }

  @Override
  public int getRating() {
    return rating;
  }

  @Override
  public String getValue() {
    return String.format("EBITDA: %.2f EBITDA Margin: %.2f", EBITDA, EBITDAMargin);
  }
}
